site_name: ERPAL Platform Docs
repo_url: https://github.com/brightsolutions/ERPAL-Platform-Docs
pages:
- [index.md, 'Home']
- [termdefinitions.md, 'Termdefinitions']
- [usecases.md, 'Use cases']
- [about.md, 'About']
theme: readthedocs
