site_name: ERPAL Platform Docs
repo_url: https://github.com/brightsolutions/ERPAL-Platform-Docs
site_description: Project documentation for ERPAL Platform

pages:
- Home: 'index.md'
- 'Introduction':
    - 'About ERPAL': 'introduction/about_erpal.md'
    - 'About this documentation': 'introduction/about_docs.md'
    - 'Roles in this documentation': 'introduction/roles.md'
    - 'Contributing to ERPAL Platform': 'introduction/erpal_contrib.mb'
#- [concepts/index.md, 'Concepts', 'Termdefinitions']
- 'Concepts':
    - 'Product (bundle of entity product)': 'concepts/product.md'
    - 'Line item': 'concepts/line-item.md'
    - 'Deliveries': 'concepts/deliveries.md'
    - 'Revenue': 'concepts/revenue.md'
    - 'Quote': 'concepts/quote.md'
    - 'Order': 'concepts/order.md'
    - 'Invoice': 'concepts/invoice.md'
    - 'Taxes': 'concepts/taxes.md'
    - 'Project': 'concepts/project.md'
    - 'Budgets': 'concepts/budgets.md'
    - 'Audit-proof': 'concepts/audit-proof.md'
    - 'Use cases': 'usecases/usecases.md'
- 'Development':
#    - 'Development': 'development/development.md'
    - 'Comments': 'development/comments.md'
    - 'Creating a sub-theme': 'development/subtheme.md'
    - 'How to change a menu icon': 'development/change-menu-icon.md'
#    - 'How to enable eu-vat': 'development/enable-euvat.md'
    - 'Custom product- and line-item-types': 'development/custom-product-lineitem-type.md'

theme_dir: erpaltheme
